import { Inter } from 'next/font/google'
import '@/styles/globals.css';
import './globals.css'
import { AuthContextProvider } from '../lib/context/AuthContext'

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'NHS TutorMe',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        <AuthContextProvider>
          {children}
        </AuthContextProvider>
      </body>
    </html>
  )
}
