export const RequestStatus = {
  PENDING: "PENDING",
  MATCHED: "MATCHED",
  TUTOR_CONFIRMED: "TUTOR_CONFIRMED",
  STUDENT_CONFIRMED: "STUDENT_CONFIRMED",
  PENDING_ADMIN: "PENDING_ADMIN",
  APPROVED: "APPROVED",
  DENIED: "DENIED",
};
